apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-financial.fullname" . }}
  labels:
    {{- include "rag-financial.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: 8001
  selector:
    {{- include "rag-financial.selectorLabels" . | nindent 4 }}
